services:
  mariadb:
    image: mariadb
    container_name: bookstore-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  #bookstore:
  #  image: bookstore
  #  container_name: bookstore-app
  #  tty: true
  #  stdin_open: true
volumes:
  db_data:
